require("lualine").setup({
	options = {
		icons_enabled = true,
		theme = "auto",
		-- theme = 'pywal-nvim',
		component_separators = { left = " ", right = " " },
		section_separators = { left = " ", right = " " },
		-- component_separators = { left = '', right = ''},
		-- section_separators = { left = '', right = ''},
		disabled_filetypes = {},
		always_divide_middle = true,
	},
	sections = {
		lualine_a = { "mode", bg = nil },
		lualine_b = { "branch",  "diagnostics" },
		lualine_c = { "%=","%t%m"},
		lualine_x = { "filetype" },
		lualine_y = { "" },
		lualine_z = { "location", "progress" },
	},
	inactive_sections = {
		lualine_a = {},
		lualine_b = {},
		lualine_c = { "filename" },
		lualine_x = { "location" },
		lualine_y = {},
		lualine_z = {},
	},
	tabline = {},
	extensions = {},
})
