require("plugins")
require("impatient")
require("general.settings")
require("general.keymaps")
require("plugin.session_manager")
require("plugin.window_picker")
require("plugin.indent_lines")
require("plugin.rich_presence")
require("plugin.transparent")
require("plugin.start_page")
require("plugin.autosave")
require("plugin.LSP")
require("plugin.explorer")
require("plugin.which_key")
require("plugin.barbar")
require("plugin.treesitter")
require("plugin.org")
require("plugin.completion")
require("plugin.luasnip_conf")
require("plugin.comment")
require("plugin.highlightStr")
require("plugin.autopairs")
require("plugin.status_bar")
require("plugin.tog_term")
require("plugin.git_signs")
require("plugin.format.format")
require("general.colorscheme")
require("plugin.cursor_context")
require("general.highlights")
require("plugin.telescope_conf")
-- require("plugin.winbar_config")
vim.o.winbar = "%{%v:lua.require'nvim-navic'.get_location()%}"
if vim.g.neovide then
	vim.cmd([[
        set guifont=Comic\ Code\ Ligatures:h13
    ]])
	vim.g.neovide_transparency = 1
end
