require("user.settings")
require("manager")
require("user.keymaps")
require("impatient")
require("user.autocmds")
require("plugin.lsp")
-- require("range-highlight").setup()
-- require("Navigator").setup()

-- require("plugin.autosave")
if vim.g.neovide then
	require("user.neovide")
else
	require("user.colorscheme")
end
require("plugin.treesitter")
-- require("plugin.treesitter_context")
require("plugin.org")
require("plugin.completion")
require("plugin.luasnip_conf")
require("plugin.comment")
require("plugin.autopairs")
require("plugin.status_bar")
require("plugin.tog_term")
require("plugin.git_signs")
require("plugin.format.format")
-- require("plugin.cursor_context")
require("plugin.telescope_conf")
require("plugin.due_conf")
require("plugin.ufo_conf")
