require("plugins")
require("impatient")
require("user.settings")
--require("user.autocmds")
require("user.colorscheme")
require("user.keymaps")
require("plugin.lsp")
require("user.highlights")
-- require("plugin.session_manager")
require("plugin.window_picker")
--require("plugin.fold_prev")
require("plugin.indent_lines")
require("plugin.rich_presence")
require("plugin.transparent")
require("plugin.start_page")
require("plugin.autosave")
require("plugin.explorer")
require("plugin.which_key")
require("plugin.cybu_conf")
require("plugin.buf_deleto")
require("plugin.barbar")
require("plugin.treesitter")
require("plugin.treesitter_context")
require("plugin.org")
require("plugin.completion")
require("plugin.luasnip_conf")
require("plugin.comment")
require("plugin.highlightStr")
require("plugin.autopairs")
require("plugin.status_bar")
require("plugin.tog_term")
require("plugin.git_signs")
require("plugin.format.format")
require("plugin.cursor_context")
require("plugin.telescope_conf")
--[[ require("plugin.winbar_config") ]]
if vim.g.neovide then
	vim.cmd([[
        set guifont=Comic\ Code\ Ligatures:h13
    ]])
	vim.g.neovide_transparency = 1
end
