#!/bin/sh
# alias j='z'
# alias f='zi'
# alias g='lazygit'
# alias zsh-update-plugins="find "$ZDOTDIR/plugins" -type d -exec test -e '{}/.git' ';' -print0 | xargs -I {} -0 git -C {} pull -q"




####################################################
#MY ALIAS
alias PJC="cd ~/Documents/Projects/Course/" #dir shortcut 
alias PJP="cd ~/Documents/Projects/Personal/" #dir shortcut 
alias PJT="cd ~/Documents/Projects/Testing/" #dir shortcut 
alias nvimrc='nvim ~/.config/nvim/init.lua' #open nvimrc
alias python='python3.8' #open nvimrc
alias poweroff='systemctl poweroff' #turning off pc 
alias anime='~/Apps/ani-cli/ani-cli' #anime cli
alias se='du -a ~/.config/* ~/Documents/Projects/* | awk "{print $2}" | fzf | xargs -r $EDITOR ; '
alias todo='nvim ~/Documents/neorg/gtd/index.norg'
alias jspg='nvim ~/Documents/Projects/Testing/webDev/playground/app.js'
alias pypg='nvim ~/Documents/Projects/Testing/python/PPG/playground.py'
alias gopg="nvim ~/Documents/Projects/Testing/go/playground/pg.go"
alias shpg='nvim ~/Documents/Projects/Testing/bashScript/playground/playground.sh'
alias luapg='nvim ~/Documents/Projects/Testing/lua/playground/playground.lua'
alias tmux='tmux -f ~/.config/tmux/.tmux.conf -u'
alias journal="nvim ~/Documents/norg/index.norg"
alias yt-dlp='yt-dlp --config-locations "~/.config/yt-dlp.conf"'
alias pomodoro="go run ~/Documents/Projects/Personal/pomodoro/main.go"
#####################################################


# alias lvim='nvim -u ~/.local/share/lunarvim/lvim/init.lua --cmd "set runtimepath+=~/.local/share/lunarvim/lvim"'

# get fastest mirrors
alias mirror="sudo reflector -f 30 -l 30 --number 10 --verbose --save /etc/pacman.d/mirrorlist"
alias mirrord="sudo reflector --latest 50 --number 20 --sort delay --save /etc/pacman.d/mirrorlist"
alias mirrors="sudo reflector --latest 50 --number 20 --sort score --save /etc/pacman.d/mirrorlist"
alias mirrora="sudo reflector --latest 50 --number 20 --sort age --save /etc/pacman.d/mirrorlist"

# Remarkable
alias remarkable_ssh='ssh root@10.11.99.1'
alias restream='restream -p'

# Colorize grep output (good for log files)
alias grep='grep --color=auto'
alias egrep='egrep --color=auto'
alias fgrep='fgrep --color=auto'

# confirm before overwriting something
alias cp="cp -i"
alias mv='mv -i'
alias rm='rm -i'

# easier to read disk
alias df='df -h'     # human-readable sizes
alias free='free -m' # show sizes in MB

# get top process eating memory
alias psmem='ps auxf | sort -nr -k 4 | head -5'

# get top process eating cpu ##
alias pscpu='ps auxf | sort -nr -k 3 | head -5'

# gpg encryption
# verify signature for isos
alias gpg-check="gpg2 --keyserver-options auto-key-retrieve --verify"
# receive the key of a developer
alias gpg-retrieve="gpg2 --keyserver-options auto-key-retrieve --receive-keys"

# For when keys break
alias archlinx-fix-keys="sudo pacman-key --init && sudo pacman-key --populate archlinux && sudo pacman-key --refresh-keys"

# systemd
alias mach_list_systemctl="systemctl list-unit-files --state=enabled"

alias mach_java_mode="export SDKMAN_DIR="$HOME/.sdkman" && [[ -s "$HOME/.sdkman/bin/sdkman-init.sh" ]] && source "$HOME/.sdkman/bin/sdkman-init.sh""

alias m="git checkout master"
alias s="git checkout stable"

case "$(uname -s)" in

Darwin)
	# echo 'Mac OS X'
	alias ls='ls -G'
	;;

Linux)
	alias ls='ls --color=auto'
	;;

CYGWIN* | MINGW32* | MSYS* | MINGW*)
	# echo 'MS Windows'
	;;
*)
	# echo 'Other OS'
	;;
esac
